### ISSUE TITLE
readme?

### ISSUE THREAD

**Issue by ligaoyi101** [CSCI599-Lim-Squad/clothesGAN#2]
Hello,thanks for your sharing!
I am very interested in your ClothesGAN.
since the "readme" description is about cycleGAN, so..what about this project? Could you upload some description about this project? 
thank you very much!!
I am looking forward your reply : )

**Comment by AustinZzx** [comment]
Here's the blog of our project, and that might have the details you're looking for.

https://csci599-lim-squad.github.io/clothesGAN.github.io/2017/11/27/Clothes-Style-Transfer-with-Cycle-GAN/
